[WIP] Creating basic structure of application
marmelab/quarto-android pull request #1
Opened 2018-06-26 10:11 UTC by JulienMattiussi

Defining pages of the game and basic navigation between them

![image](https://user-images.githubusercontent.com/39904906/41904944-0581b490-793a-11e8-9df1-b325a92b99a7.png)

2018-06-26 11:53 UTC, djhi commented
What's left for RFR ? Can you add a checklist in your PR description ?

2018-06-26 11:54 UTC, djhi requested changes
Can you add eslint and prettier ? Ping me if you need help to configure them correctly

2018-06-26 11:56 UTC, djhi requested changes
I'm not fan of the types oriented files organization as it usually makes it a lot harder to reason about a feature. You should create a folder for each route and keep all the components specific to each route in its folder. If you have some components used in more than one route, introduce a `lib` or `components` folder at the project src

2018-06-26 12:13 UTC, djhi commented on routes/GameListScreen.js
> +      navigation.navigate('Home', {
Why the empty object parameter ?

2018-06-26 12:14 UTC, djhi commented on routes/GameScreen.js
> +      navigation.navigate('Home', {
Why the empty object parameter ?

2018-06-26 12:14 UTC, djhi requested changes

2018-06-26 12:14 UTC, djhi commented on routes/HomeScreen.js
> +      navigation.navigate('Game', {
Why the empty object parameter ?

2018-06-26 12:14 UTC, djhi commented on routes/HomeScreen.js
> +      navigation.navigate('GameList', {
Why the empty object parameter ?

2018-06-26 15:43 UTC, djhi reviewed
Don't forget to run eslint on all your files

```sh
./node_modules/.bin/eslint --fix ./src
```

2018-06-27 08:55 UTC, djhi requested changes
One last thing, we need a travis.yml file

2018-06-27 09:13 UTC, djhi approved these changes

2018-06-27 09:39 UTC, merged

2018-06-27 14:30 UTC, JulienMattiussi commented
Slack est down, d'ou le mail
Tu a un peu de temps pour un call ?

https://appear.in/quarto-android



2018-06-27 11:39 GMT+02:00 Gildas Garcia <notifications@github.com>:

> Merged #1 <https://github.com/marmelab/quarto-android/pull/1>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/marmelab/quarto-android/pull/1#event-1703434664>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AmDmitD-tlQSRWl-c-ThkoQ7ujyzEjiMks5uA1LggaJpZM4U3o2p>
> .
>